name: 🌟 Enhancement Request
description: Suggest your enhancement for the existing Features
title: "[Enhancement]: "

body:
  - type: checkboxes
    attributes:
      label: "Is there an existing issue for this?"
      description: "Please search to see if an issue already exists for the bug you encountered."
      options:
        - label: "I have searched the existing issues"
          required: true
  - type: textarea
    id: enhancement-description
    attributes:
      label: "Issue Description ✍️"
      description: Enter a brief description about the Feature Enhancement
      placeholder: Please include a summary, also include relevant motivation and context.
      value: |
        ## 📌 Issue Summary  
        <!-- Provide a brief summary of the issue --> 

        ## 📷 Screenshot  
        <!-- Attach screenshots if applicable -->

        ## 💡 Suggestions  
        <!-- Any ideas for a fix? -->
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Record"
      options:
        - label: "I have synced all my node versions as mentioned in the project"
          required: true
        - label: "I am using the same version of npm as is the project"
          required: true
        - label: "My current branch is in sync with the development branch"
          required: true
        - label: "I want to work on this issue"
          required: false
