name: Create preview environment

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

concurrency:
  group: codepreview
  cancel-in-progress: false

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies
        run: |
          cd client
          npm ci

      - name: Build Next.js Project
        run: |
          cd client
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/out
